#
#  yml的优先级会大于properties,所以如果同时存在这两种配置,因为properties是后加载的,所以此时yml就没有生效
#
# 配置文件规则如下：
# 1、文件命名需要符合application-{profile}.yml的格式，如：application-dev.yml
# 2、通用配置写到application.yml中，不同的环境配置写到不同的yml文件中
#
#
spring:
  profiles:
    active: dev   #激活需要使用的 application-{profile}.yml
  config:
    pvUrl: http://8.130.39.240:5050/guangfu
    needEncrypt: false #是否需要对接口返回数据进行 加密
    needDecrypt: false #是否需要对接收请求参数进行 解密
    secretKey: efsdfe124587jshqcgszmghstcw54735 #AES加密私钥 32字节
    secretIv: 553456qwdscfrtgb #AES密钥向量 16字节
    encryptMd5Soft: efuav201603 #账户密码MD5加盐
    videoStreamStorage: false #流媒体服务器，true:自定义,false:云服务器f
    singleOn: false  #true 开启单点 false 关闭单点
    # 光伏项目公钥，私钥
    publishGuangfu: false #是否自动推送光伏检测数据
    PhotoStorage: false #照片储存 true存本地 false存minio 查看 删除照片也是
    DatabaseStorage: true #数据库储存 true 开始存
    rsaPublicKey_pro_guangfu: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArQmpjAneqZ64ujSqaoVhFnch/MemFB6x2WEZKgreB8Tic3/qXoThRF/FYcbXcWeAIMlO+7szId/Dk3xTYuY5BZSI+it1EZZUjgduI3LZk56xQkZsdsGRpok6xsBD1RDgTG7mhf6pUkHd/xaqZEAcDtbwTcD9ocdTIBKKz2Rg5xAApUz69Rqrn7PRZUg+6ejlPtcYnbhwm5YfQYddgU3m/7sCjAvWAEhDT/8XlRWB/SDmnxEsKflg55gJKEdI2MutD/m6Gm9bCBTnNib9J+v3XqPYEhCLlHvT4y1/9Yi1v2wxb4ymk4HUJSDnmGpgXfrb3B/BjykV2rqjrIYkCAGv6QIDAQAB
    rsaPrivateKey_pro_guangfu: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtCamMCd6pnri6NKpqhWEWdyH8x6YUHrHZYRkqCt4HxOJzf+pehOFEX8VhxtdxZ4AgyU77uzMh38OTfFNi5jkFlIj6K3URllSOB24jctmTnrFCRmx2wZGmiTrGwEPVEOBMbuaF/qlSQd3/FqpkQBwO1vBNwP2hx1MgEorPZGDnEAClTPr1Gqufs9FlSD7p6OU+1xiduHCblh9Bh12BTeb/uwKMC9YASENP/xeVFYH9IOafESwp+WDnmAkoR0jYy60P+boab1sIFOc2Jv0n6/deo9gSEIuUe9PjLX/1iLW/bDFvjKaTgdQlIOeYamBd+tvcH8GPKRXauqOshiQIAa/pAgMBAAECggEBAINjudT2zZbYSYZCZUA7BOyNC0aoxmeyovLfsr7kv5EAo751251norFLU1IaLQ8UOwsqMIoerAXFpfjAR4TqMVQWZCgphVwUXSH3bF8IX0OjFQ+w770A4DqnKvUtmpQXm2kOMIaAR0uJbiq6qCk1MNjnxlIT/8Ku2mSZD8PIgXgQveFGkzY6fHLL46NuR9GxpTTBAaEUhydqOvZayGE5OCCIJulASpaMTChySNSRctmQz99Slkdc9OwW93nd906OwDMrhopSV3uY4iYsIXYDH8w2/NX83zMcRSYltYpF4dmnJPdpWsZ7KBOqK640YuFAuTlXJSEfihAXNV4DHJzkuvECgYEA/9A395fm3oPtfrTizMl5rT7nB9zThKyK4JoUWWFabFrhHTC1YzDV95T0ZhoN4aYBcvu1Clj/SZKutNcdd69tDxQn9/3adN31NmJMjMOm8jo0KQdG0EKj05Cuv6S+m2vf8VC8Lh3AK6vx5TmKNiqajO0BquvebbTPVRav1xfUZfUCgYEArSn7j7WDLPJpgCnsJ8ZpFP7MvKsHn9qP6Uz0qo+goIC0jPF9ri1ncqTh9BdAxezU0eNAMzxG+5fJ/KMTOiaQy/RMuIdIK+2IBnnjCDOkUh8D41hgiySDoHrvlFi8QOa+gLXcsqIvCP5EgC9Utd9hd/CKZqmbAYnx93LWX96XdaUCgYEA85aMxInzf+z2CBIsaL5sy6g7DASdsRcvguGVAOsv1D/RXh9UiWgmRoOjGVoz36tYc+n0oS7PoHo5O+Aeoin8WkBiMsWZ8HCuH6QIqn1figYcRvkz1/ms0DdT/w7bpVlaPAoZtnwD0lH/m7tnvV5iHlFMpjnFaoeiaa6Zr+J0EMUCgYAXiiZ9YbJkUMvQtWI6AfnU9dJFL4bIz0BS+bgk24N9biGdK1Lnc5qldg6VTPfsMAa6RYc7r80CdJ7rrgt2EzoJz7sCNrmz5wVfw//95G9JDphLtn7hS2RtU2jwJKPqurNY8d//lJaKRW5wcn60fppUYKmfzRyaN/NhrQXBYJP8VQKBgFWWhwmip1QoBgDwIe0NxiXsS0Syl/WxpPoooxNJ+hSBUoJMm1bO+IEFPgZ+kIPDGY4VbyqZiB63sf+zD2ncJsiiRqAluYggrOqtilMGbTHBEwGaghbhD8xf236c88Ry7oXM9XM5FXhBIwAAcJ3X84qVf/E1VpSSnEebM9Rv3AMd
  mqtt:
    protocol: tcp
    host: 8.148.10.90
    port: 1883
    user: reseeding
    pwd: 6LqQyMQ7!fP
    subscribeTopicHive: efuav/HiveC/# #订阅机巢主题
    subscribeTopicEfuav: efuav/uavappC/# #订阅翼飞无人机主题
    subscribeTopicDjiUav: efuav/djiappC/# #订阅大疆无人机主题
    publishTopicHive: efuav/HiveS/# #发布公共机巢主题
    publishTopicEfuav: efuav/uavappS/# #发布公共翼飞无人机主题
    publishTopicDjiUav: efuav/djiappS/# #发布公共大疆无人机主题
  jwt:
    jwtKey: efuavvsq02148d0e855e0000a6a0eqwe #签名私钥 32字节
    timeOut: 10800000 #签名有效时间毫秒
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:c:\efuav\UavSystem
  servlet:
    multipart:
      max-file-size: 3072MB # 单个文件大小
      max-request-size: 3072MB # 设置总上传的数据大小
      enabled: true #开启
app:
  version: '@project.version@'
  buildtime: '@timestamp@'
jasypt:
  encryptor:
    password: efuav1603pvi
    algorithm: PBEWithMD5AndDES
#minio:
#  AccessKey: efuav
#  SecretKey: efuavminio~xz222y!1dsd6
#  BucketName: efuav
#  BucketNameKmz: efuavkmz
#  BucketNameWord: efuavword
#  Endpoint: http://8.148.10.90:9000
#  EndpointExt: http://8.148.10.90:9000
TxyTrtc:
  TxyTrtcSdkAppId: 1400739024 # 腾讯云服务器 ,音视频通话SDK
  TxyTrtcExpireTime: 604800 # 过期时间，7天
  TxyTrtcSecretKey: e364909a702f53e1702412a4e130d98187f66a2ecca22dd4f382de1e2e6c276d # 秘钥
tencent:
  # 腾讯云储存桶签
  TxyBucketName: efuav-1302980652
  TxyPrefix: https://efuav-1302980652.cos.ap-shanghai.myqcloud.com/
  #腾讯云视频流 TxySecretStreamKey 播放
  TxySecretStreamKey: c4AYe5E2biQdKbe3mCWK
  TxyDomainName: 146099.livepush.myqcloud.com
  TxyTemplateid: 28453
  TxyPlayName: www.efuav.ltd
  # 腾讯云直播服务器签名
  TxySecretId: AKIDuc3D6i37uRiiRu88sSoujHZaKn0yf5E7
  TxySecretKey: e1A4h4AzYqsfDUVFiupSpvkIYXGhrlPn
  #腾讯云短信 陶沙账户
  #腾讯云账户密钥对: secretId 注册时上面提到的要用的secretId
  #陶沙账户
  SMSSECREID: AKIDuc3D6i37uRiiRu88sSoujHZaKn0yf5E7
  #腾讯云账户密钥对: secretKey 注册时上面提到的要用的secretKey
  SMSSECREKEY: e1A4h4AzYqsfDUVFiupSpvkIYXGhrlPn
  #短信 appid，按照此路径查找：短信》》应用管理》》应用列表》》系统默认应用》》SDKAppID
  SMSAPPID: 1400705870
  #申请的模版ID
  TEMPLATEID: 1473373
  #短信注册ID
  SMSREGISTERID: 1473397
  #秸秆焚烧模板ID
  STRAWID: 1761884
# root日志级别
logging:
  #  config: classpath:logback/logback.xml
  config: classpath:logback.xml
  level:
    # root日志级别设置  trace/debug/info/warn/error
    root: warn
    org:
      hibernate: error
      springframework:
        web: warn
        security: warn

